### ISSUE TITLE
Kotlin daily builds

### ISSUE THREAD

**Issue by pascalgrimaud** [hipster-labs/jhipster-daily-builds#10]
Following this https://github.com/jhipster/jhipster-kotlin/pull/138#issuecomment-501978948

**Comment by Hawkurane** [comment]
I can look into this later.
Do we create a new pipeline we 10 jobs for Kotlin blueprints or do we regenerate the projects in each jobs but with Kotlin blueprints?
The former looks better if we add more blueprints tests later (looking at you vuejs...).

WDYT @pascalgrimaud

**Comment by pascalgrimaud** [comment]
new dedicated pipeline with Kotlin, similar to the config with 'official' or 'official openjdk8' pipelines

With kotlin, you can use the same app/config (.yo-rc.json)

**Comment by Hawkurane** [comment]
It seems they have their own pipelines files for ci-cd that we can reuse (or supplement) for daily builds
https://github.com/jhipster/jhipster-kotlin/blob/master/azure-pipelines.yml
and scripts that i'm probably going to copy-pasta

**Comment by Hawkurane** [comment]
pinging @pvliss to ask what kind of config you would like to test.
Since your ci-cd pipeline is almost identical to the Official/OpenJDK8 one, I think implementing new and heavier configs are more interesting there but as I don't use the Kotlin blueprint, I don't know what kind of configs you are looking out for there.

**Comment by pvliss** [comment]
Thanks for looking into this @Hawkurane. Well, the pipeline is indeed identical with the exception of one or two samples to test some extra configurations as there is currently no daily build. In fact, the KHipster blueprint supports the exact same features as the Java main generator. We can re-use all the existing samples(`.yo-rc.json`) but not sure about the pipelines. Ideally we could do the same but not sure if that is doable and maintainable(see also below). If not, then most interesting configurations would be the ones that alternate server side options. Maybe @sendilkumarn also has some extra thoughts regarding this?

I think I asked @pascalgrimaud before but would it be possible to have a separate repo for khipster daily builds in order to have all the pipelines of interest(instead of just 1-2) and re-use all samples(`yo-rc.json`) from this repo? Are there any limitations in Azure or do you think it would be very hard to maintain?

**Comment by sendilkumarn** [comment]
That is a very valid point @pvliss 

AFAICT, it would be great if we have separate repos for this. Because it will not be an overhead for anyone maintaining it. But if there are limitations, then we have to think about it.

**Comment by Hawkurane** [comment]
As far as I remember, each azure organization gets 10 parallel agents that can work at the same time. This means we can make another organization (e.g. khipster-daily-builds) which would be basically the fork from this repo and just changing the scripts to make sure the khipster blueprint is used.

@pascalgrimaud should be the one making the org imo if there should ever be a new azure organization/account

**Comment by pascalgrimaud** [comment]
Opened for too long, let's close this
