### ISSUE TITLE
Daily builds for Windows

### ISSUE THREAD

**Issue by pascalgrimaud** [hipster-labs/jhipster-daily-builds#28]
Asked by @pmverma here: https://github.com/jhipster/generator-jhipster/issues/10662#issuecomment-544601312

I'll try to add this pipeline when possible
@Hawkurane has the permission to do it too

I can add more admins if needed. Just ask !

**Comment by pmverma** [comment]
@pascalgrimaud Can you please add me?

**Comment by pascalgrimaud** [comment]
@pmverma : can you mail me your microsoft account ?

**Comment by SudharakaP** [comment]
@pascalgrimaud : Would you mind adding me to as well (to the organization and the azure account)? :wink: 

@pmverma : Would you be okay if I go ahead and configure this one? I want to learn Azure pipelines better. :smile:

**Comment by SudharakaP** [comment]
I've added the Windows pipeline in the above two PRs. The generator needed to have a small workaround since otherwise ShellJS seems to fail in this windows build machines. I've also scheduled it at 16:30 (UTC) and added it to the readme. Please merge https://github.com/jhipster/generator-jhipster/pull/11140 first if you want to test it out :smile:
