### ISSUE TITLE
Builds for no database

### ISSUE THREAD

**Issue by pascalgrimaud** [hipster-labs/jhipster-daily-builds#8]
Following this https://github.com/jhipster/generator-jhipster/pull/9674#issuecomment-489778285
It would be 6 builds :
- Angular + Maven + JWT + no database
- Angular + Maven + Session + no database
- Angular + Maven + OAuth2 + no database
- React + Gradle + JWT + no database
- React + Gradle + Session + no database
- React + Gradle + OAuth2 + no database

**Comment by cbornet** [comment]
Thanks for the builds.
No database + Oauth2 hasn't been merged yet : https://github.com/jhipster/generator-jhipster/pull/9648
Session and JWT should be fixed by : https://github.com/jhipster/generator-jhipster/pull/9718
React should be fixed by : https://github.com/jhipster/generator-jhipster/pull/9711

**Comment by pascalgrimaud** [comment]
I updated my list. I did 6 builds, mixing Angular + Maven, and React + Gradle

**Comment by pascalgrimaud** [comment]
already done, recently
